### ISSUE TITLE
Error RunningDeepPhospho GUI

### ISSUE THREAD

**Issue by ezarzuela** [weizhenFrank/DeepPhospho#5]
Hello,
I previously used DeepPhospho from the web server and I am very happy with the results, but now I see that unfortunately the web version no longer operative.
I tried running DeepPhospho using the GUI ( I downloaded the zip file from [release page](https://github.com/weizhenFrank/DeepPhospho/releases) using the demo data (Example 2 (use existed model weight files to do prediction without training and turn off RT ensemble)) but I got the following error:

C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\cuda\__init__.py:81: UserWarning:
    Found GPU0 Quadro K420 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
2022-11-30 15:11:08,895 DeepPhosphoRunner ERROR:
ERROR: Error when running ion model prediction instance 20221130_151107-20221130_145828ee_20221130_151107-IonPred-PredInput-Format_PepDP
Traceback (most recent call last):
  File "C:\DeepPhospho\deep_phospho\train_pred_utils\runner.py", line 268, in pred_ion
    stat = pred_ion(configs=cfg_cp, termin_flag=self.termin_flag)
  File "C:\DeepPhospho\deep_phospho\train_pred_utils\ion_pred.py", line 158, in pred_ion
    model = model.to(device)
  File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 612, in to
    return self._apply(convert)
  File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 381, in _apply
    param_applied = fn(param)
  File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

Traceback (most recent call last):
  File "C:\DeepPhospho\deep_phospho\train_pred_utils\runner.py", line 268, in pred_ion
    stat = pred_ion(configs=cfg_cp, termin_flag=self.termin_flag)
  File "C:\DeepPhospho\deep_phospho\train_pred_utils\ion_pred.py", line 158, in pred_ion
    model = model.to(device)
  File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 612, in to
    return self._apply(convert)
  File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 381, in _apply
    param_applied = fn(param)
  File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepPhospho\run_deep_phospho.py", line 368, in <module>
    DeepPhosphoRunner(args, start_time=start_time, msgs_for_arg_parsing=msgs)
  File "C:\DeepPhospho\deep_phospho\train_pred_utils\runner.py", line 70, in __init__
    self.ion_pred_folders = self.pred_ion()
  File "C:\DeepPhospho\deep_phospho\train_pred_utils\runner.py", line 278, in pred_ion
    raise RuntimeError(error_msg)
RuntimeError: ERROR: Error when running ion model prediction instance 20221130_151107-20221130_145828ee_20221130_151107-IonPred-PredInput-Format_PepDP

Could you help me? Thanks!

**Comment by weizhenFrank** [comment]
Hi this is Frank Liu, one of the developers of this tool. From the error information, it seems like your graphic card might be a little old as the cuda version is 3.0 but the minimum requirement is 3.5. So my suggestion is to upgrade your cuda version of your graphic card or use a more advanced graphic card whose cuda version is bigger than 3.5.Thanks & Best Wishes Weizhen LiuOn Nov 30, 2022, at 10:25 AM, ezarzuela ***@***.***> wrote:﻿
Hello,
I previously used DeepPhospho from the web server and I am very happy with the results, but now I see that unfortunately the web version no longer operative.
I tried running DeepPhospho using the GUI ( I downloaded the zip file from release page using the demo data (Example 2 (use existed model weight files to do prediction without training and turn off RT ensemble)) but I got the following error:
C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\cuda_init_.py:81: UserWarning:
Found GPU0 Quadro K420 which is of cuda capability 3.0.
PyTorch no longer supports this GPU because it is too old.
The minimum cuda capability that we support is 3.5.
warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
2022-11-30 15:11:08,895 DeepPhosphoRunner ERROR:
ERROR: Error when running ion model prediction instance 20221130_151107-20221130_145828ee_20221130_151107-IonPred-PredInput-Format_PepDP
Traceback (most recent call last):
File "C:\DeepPhospho\deep_phospho\train_pred_utils\runner.py", line 268, in pred_ion
stat = pred_ion(configs=cfg_cp, termin_flag=self.termin_flag)
File "C:\DeepPhospho\deep_phospho\train_pred_utils\ion_pred.py", line 158, in pred_ion
model = model.to(device)
File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 612, in to
return self._apply(convert)
File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
module._apply(fn)
File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 381, in _apply
param_applied = fn(param)
File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 610, in convert
return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
Traceback (most recent call last):
File "C:\DeepPhospho\deep_phospho\train_pred_utils\runner.py", line 268, in pred_ion
stat = pred_ion(configs=cfg_cp, termin_flag=self.termin_flag)
File "C:\DeepPhospho\deep_phospho\train_pred_utils\ion_pred.py", line 158, in pred_ion
model = model.to(device)
File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 612, in to
return self._apply(convert)
File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
module._apply(fn)
File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 381, in _apply
param_applied = fn(param)
File "C:\DeepPhospho\DeepPhosphoPythonEnv\lib\site-packages\torch\nn\modules\module.py", line 610, in convert
return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\DeepPhospho\run_deep_phospho.py", line 368, in 
DeepPhosphoRunner(args, start_time=start_time, msgs_for_arg_parsing=msgs)
File "C:\DeepPhospho\deep_phospho\train_pred_utils\runner.py", line 70, in init
self.ion_pred_folders = self.pred_ion()
File "C:\DeepPhospho\deep_phospho\train_pred_utils\runner.py", line 278, in pred_ion
raise RuntimeError(error_msg)
RuntimeError: ERROR: Error when running ion model prediction instance 20221130_151107-20221130_145828ee_20221130_151107-IonPred-PredInput-Format_PepDP
Could you help me? Thanks!

**Comment by gureann** [comment]
Hi @ezarzuela ,

Sorry for the problem of web service. And thanks for reporting it. We'll address it these days.

For the desktop version, as the error messages mentioned, the GPU 0 (Quadro K420) on your computer has relatively lower cuda capability, which means it's not enough to do computation for PyTorch. 
You might want to choose another graphic card if these is, by changing the value `0` in `general config panel` to another value (perhaps `1`). 
You can also do prediction with cpu by setting this `0` to `cpu` (only cpu is fine and no other symbol)

BTW, in example 2 we turned off RT ensemble for faster running but it will slightly harm the accuracy. It's a trade off of running time and accuracy.

**Comment by ezarzuela** [comment]
Hi Frank and Ronghui,
I performed the prediction using the cpu as you said and it worked perfectly.
Many thanks for your quick answer!

Eduardo
